### ISSUE TITLE
Start Bug

### ISSUE THREAD

**Issue by IM-studios** [carcarjg/Klara#18]
**Describe the bug**
Klara will not start.

**To Reproduce**
1. Go to 'File browser - Debug - Debug '
2. Click on 'Klara.exe'
4. See error 'Program will not show interface'

**Expected behavior**
the program starting and showing interface.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [Version of what?]

**Additional context**
.Net Framework 4.8 Dev Pack Installed.
Debug.Zip was opened normally and did not work.
Debug.7z was opened with 7zip and did not work.
unable to delete files after running and error stating that file is open in another program is seen. 
No files were deleted, moved, or coped before attempt to open program was made.
Program cannot not be viewed in Task Manager.

**Comment by IM-studios** [comment]
Here you are.

**Comment by IM-studios** [comment]
I installed every thing except NuGET.

**Comment by carcarjg** [comment]
Yep, I don’t know what’s wrong. So you say it might be running in the background?

**Comment by IM-studios** [comment]
yes I cant delete the folder.

**Comment by carcarjg** [comment]
You don’t need to install nuget its just for development. All the nessasary dlls are in the folder

**Comment by IM-studios** [comment]
But after I restarted my computer I could.

**Comment by carcarjg** [comment]
Odd. When you try and open the exe wait a few seconds then look down on the task bar near the clock and see if you see a square with the same icon as the exe

**Comment by IM-studios** [comment]
My dad said that because there is no installer.  The program cannot get or download all the library's it needs.

**Comment by IM-studios** [comment]
okay, trying that.

**Comment by carcarjg** [comment]
All the library’s it need besides .net are in the folder. I’ve run it on blank vms where the only thing they had was .net core and framework and the folder and it worked.. don’t know why it’s not for you

**Comment by IM-studios** [comment]
Nope nothing appeared.  And my computer keeps giving me security alerts.

**Comment by carcarjg** [comment]
Oh? What type?

**Comment by IM-studios** [comment]
hold on, I may need to restart my computer to get it again.

**Comment by IM-studios** [comment]
Restarting.

**Comment by carcarjg** [comment]
The issue may be the fact that the version on github was compiled in debug and not Release.

**Comment by IM-studios** [comment]
sorry for the wait I just restarted my computer.  And yes both files I downloaded were labeled Debug.zip and Debug.7z

**Comment by carcarjg** [comment]
Yep. Let me switch It out for the Release version. I believe that may be part of the problem

**Comment by IM-studios** [comment]
Okay.

**Comment by carcarjg** [comment]
After closer inspection it was found 1)a core library was not shipped with the program and 2) the program on github was not intended for release

**Comment by IM-studios** [comment]
Okay, awesome.

**Comment by IM-studios** [comment]
I hope it works this time>

**Comment by IM-studios** [comment]
when you zip it.  You can use 7zip I got it installed.

**Comment by IM-studios** [comment]
When will it be ready?

**Comment by carcarjg** [comment]
Working out some package problems

**Comment by IM-studios** [comment]
okay.

**Comment by carcarjg** [comment]
New build just got put up. It should work now

**Comment by IM-studios** [comment]
okay.  Downloading.

**Comment by IM-studios** [comment]
Extracting...

**Comment by IM-studios** [comment]
It works! Installing.

**Comment by carcarjg** [comment]
Cool glad the new installer works

**Comment by IM-studios** [comment]
Now the Program itself.

**Comment by carcarjg** [comment]
Awesome!

**Comment by carcarjg** [comment]
After compiling in release program loads. Issue closed.

**Comment by IM-studios** [comment]
After running the installer the program wont work.

**Comment by carcarjg** [comment]
In what way? Does it open?

**Comment by IM-studios** [comment]
I started a new Bug Report.

**Comment by carcarjg** [comment]
K

**Comment by IM-studios** [comment]
Issue #19
