### ISSUE TITLE
Program wont start

### ISSUE THREAD

**Issue by IM-studios** [carcarjg/Klara#9]
**Describe the bug**
Klara in windows

**To Reproduce**
1. Go to 'file browser'
2. Click on 'Klara.exe'
3. Program start 'the program will not start even as administrator'
4. 'wait'

**Expected behavior**
program starting.

**Screenshots**
none.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [unknown]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by carcarjg** [comment]
> **Tests run**
> Blank vm test times 3 (1 windows 10 home, 1 pro, 1 enterprise)
> Loaded vm (windows 8.1)
> _note all tests run on both intel and amd hardware_
> 
> **Results**
> In All Vm and physical Machine tests the program loaded and functions as normal. Could be caused by a file being deleted by the reporting party. Or could be malware related. Will investigate further.

Tested on windows 7 vm's. Program loads on all but a non SP packed vm

**Comment by carcarjg** [comment]
Tested on vms without .net 4.x installed program fails to load. Consider making a note on install page or installer.

**Comment by carcarjg** [comment]
See #18
